// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-5VTVb_A5Ik2LL6dbUrWvYcvcfIGGprU',
    appId: '1:194223666212:web:1de8ad7e9191cacc6b94b1',
    messagingSenderId: '194223666212',
    projectId: 'my-first-project-8848e',
    authDomain: 'my-first-project-8848e.firebaseapp.com',
    storageBucket: 'my-first-project-8848e.firebasestorage.app',
    measurementId: 'G-WB7Q04ZX12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfzi_8sO7xaSTjlwIR5a_rY3HtXMYQuqg',
    appId: '1:194223666212:android:1c09bf4a9d2b94386b94b1',
    messagingSenderId: '194223666212',
    projectId: 'my-first-project-8848e',
    storageBucket: 'my-first-project-8848e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPMjKkLOMpo2KbChAbELsUib2GA7iamz0',
    appId: '1:194223666212:ios:748dbe31bc6db8086b94b1',
    messagingSenderId: '194223666212',
    projectId: 'my-first-project-8848e',
    storageBucket: 'my-first-project-8848e.firebasestorage.app',
    iosBundleId: 'com.example.pilem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPMjKkLOMpo2KbChAbELsUib2GA7iamz0',
    appId: '1:194223666212:ios:748dbe31bc6db8086b94b1',
    messagingSenderId: '194223666212',
    projectId: 'my-first-project-8848e',
    storageBucket: 'my-first-project-8848e.firebasestorage.app',
    iosBundleId: 'com.example.pilem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-5VTVb_A5Ik2LL6dbUrWvYcvcfIGGprU',
    appId: '1:194223666212:web:84887f453d3cb61f6b94b1',
    messagingSenderId: '194223666212',
    projectId: 'my-first-project-8848e',
    authDomain: 'my-first-project-8848e.firebaseapp.com',
    storageBucket: 'my-first-project-8848e.firebasestorage.app',
    measurementId: 'G-JRML2REQGN',
  );
}
